codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  range: 65..85
  round: down
  precision: 2

  status:
    patch: 
      default:
        informational: true
        target: auto
        base: auto
        threshold: 85%
        flags:
          - unit-patch

    project:
      default:
        informational: true
        target: auto
        base: auto
        threshold: 85%
        flags:
          - unit-project