version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: Asia/Jakarta
    reviewers:
      - "arifai"
    assignees:
      - "arifai"
    labels:
      - "bump"
      - "dependencies"
      - "dependabot"
